### ISSUE TITLE
Paths are missing install directory

### ISSUE THREAD

**Issue by RNieuwenhuis** [schloi/MARVEL#3]
When running DBprepare.py I get the following.

ERROR: marvel.conf.PATH_SCRIPTS is set to /usr/local/scripts which doesn't exist
converting fasta to db ( min read length 2000 )
/bin/sh: 1: /usr/local/bin/FA2db: not found
partitioning db ( blocksize 200 )
/bin/sh: 1: /usr/local/bin/DBsplit: not found
dusting db
/bin/sh: 1: /usr/local/bin/DBdust: not found
creating plan
/bin/sh: 1: /usr/local/bin/HPCdaligner: not found

It seems to miss the install directory and subdirectories.
Of course I can change these paths by myself, in my case it would need MARVEL/db/ in between, but just so you know.

**Comment by schloi** [comment]
I am traveling at the moment, so this took a bit longer than it should have.

Anyway, I assume you didn't specify an install path when running `configure`, so it defaulted to `/usr/local`. If so, then this is the issue here. The build system was set up to keep all the snapshots of the git in separate directories and only have symlinks point to those.
For example: install into `/path/to/marvel` will get you a `/path/to/marvel/some.hash.code.of.git.repo`
and `/path/to/marvel/bin`, with `bin` just pointing into the dir with the hash.
This was done in order to make my life easier during development. Obviously this fails when dumping things directly into `/usr/local`. Versioned dirs are now only used when  `--enable-versioned-dirs` is passed to `configure`. This should fix your issue.

**Comment by RNieuwenhuis** [comment]
Yes, it was indeed the issue sir. My bad. 

Tiny little remark. In the e.col_pacbio/do.py script the first q.process is commented and I think it is not intended.
