### ISSUE TITLE
Running Marvel on a fish

### ISSUE THREAD

**Issue by fg6** [schloi/MARVEL#5]
Dear authors,
I am trying to run Marvel on a fish, genome size about 600 Mbp. I have about 50x of PacBio data and I am using the scripts in attachment. (I started from your python script for the e.coli_pacbio)

After running for a few weeks, I had to kill the script as it was writing down more than 15TB of data, mostly
during the 'step2.py' script running. I was wondering if this is expected for this genome size and read depth, or if maybe I need to tune the parameters somehow?

While writing this I realized I had the wrong coverage setup in the step2.py script: 25 instead of 50. Do you think this could explain the long time of running and the large amount of printout?

Any suggestion would be highly appreciated, thank you!
Francesca

[scripts.tar.gz](https://github.com/schloi/MARVEL/files/1555030/scripts.tar.gz)

**Comment by schloi** [comment]
lets start with apologizing about me completely missing your issue report.

which command in step2 was it at when you killed the script ?

one of the things that I didn't add to the example scripts that are included in the repo are delete statements for the results of previous stages. So you could end up with quite a bit data sitting on disk. I usually keep the initial overlaps and overlaps just before the final LAfilter. Since most adjustments of the assembly happen by playing with LAfilter.

**Comment by fg6** [comment]
Hi,
no problem, thank you for getting back at me.
I think the script was at the LAgap step. I attached the printout for my step2.
It didn't reach the final LAfilter, which I guess it means I cannot clean up any files/overlap ?

[output_step2.log](https://github.com/schloi/MARVEL/files/1673151/output_step2.log)

Thank you!,
Francesca

**Comment by schloi** [comment]
well, you made it pretty far. When the merging after overlapping is done you can get rid of the d00* subdirs right away. After the LAstitch you could theoretically get rid of the .las files from the previous stage too. Since you will most likely never touch LAstitch's parameters.

After the overlapping the whole processing pipeline moves from CPU bound to largely IO bound. So one thing to consider might be using fewer parallel jobs in the later stages since those might just get in each others way by generating excessive IO load. Could be one of the reasons you had to wait for two weeks.

We are running a fast interconnect between on our cluster and have multiple raids joined into a distributed file systems, but even with that very IO friendly setup I only opt for 2-3 IO bound jobs on 4-5 cluster nodes in paralle.

**Comment by fg6** [comment]
Thanks!
I will try rerunning and modifying the number of jobs as you suggested, and also cleaning up the d00* folders
after the merging.

I will let you know how it goes!
Francesca

**Comment by yangxinchao** [comment]
hello , fg6 
i run marvel to assembly a fish with one node (125 RAM and 30 CPU ) , genome size 400M , the CPU times was 7d . also i want to assembly a large genome abourt 4G , i want to know how to reduce the CPU times , maybe in  paralle and how to do this , could you help me ?

**Comment by FlyPythons** [comment]
@yangxinchao 
hello, yangxinchao,
I think the CPU times can not reduced in paralle, but the running time will be greatly reduced in paralle. If you have a cluster, i think you can use the python tools [GridMARVEL](https://github.com/FlyPythons/GridMARVEL).
